from .franjahoraria import FranjaHoraria
from .trabajador import Trabajador
from .asignacion import Asignacion
from .capacidadfranja import CapacidadFranjaArea
from .credencial import Credencial
from .labor import Labor
from .sectortrabajo import SectorTrabajo
from .sistemagestion import SistemaGestion
from .supervisor import Supervisor